version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - trumpapp
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /data/db:/data/db
    ports:
      - '27018:27017'
    networks:
      - trumpapp

networks:
  trumpapp:
    driver: bridge