name: Continuous Deployment

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Pages Deploy 
      uses: maxheld83/ghpages@v0.2.1


